"""Temporary connectivity test script for Google Sheets.

Loads the token generated by generate_drive_token.py,
authenticates via google.oauth2.credentials.Credentials,
builds a Sheets v4 service, and opens a specific spreadsheet.
"""

from __future__ import annotations

import json
import os
import sys

# Allow running directly via python backend/utils/<script>.py
_current = os.path.dirname(os.path.abspath(__file__))
_backend_dir = os.path.dirname(_current)
if _backend_dir not in sys.path:
    sys.path.insert(0, _backend_dir)

from googleapiclient.discovery import build

from config.google_config import config as google_config
from services.google_auth_service import GoogleAuthService


def main() -> None:
    sheet_id = google_config.sheet_id
    if not sheet_id:
        print("Error: GOOGLE_SHEET_ID is empty in .env", file=sys.stderr)
        sys.exit(1)

    auth = GoogleAuthService(google_config.token_path)
    creds = auth.get_credentials()
    if creds is None:
        print(
            f"Error: drive_token.json not found at {google_config.token_path}",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        service = build("sheets", "v4", credentials=creds)
        sheet = service.spreadsheets().get(spreadsheetId=sheet_id).execute()

        print("Connection Successful")
        print(f"Spreadsheet Title: {sheet.get('properties', {}).get('title')}")
        print(f"Spreadsheet ID: {sheet.get('spreadsheetId')}")
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
