"""Temporary connectivity test script for Google Drive.

Loads the token generated by generate_drive_token.py,
reads the folder ID from GoogleConfig, builds a Drive v3 service,
and prints the folder metadata.
"""

from __future__ import annotations

import json
import os
import sys

# Allow running directly via python backend/utils/<script>.py
_current = os.path.dirname(os.path.abspath(__file__))
_backend_dir = os.path.dirname(_current)
if _backend_dir not in sys.path:
    sys.path.insert(0, _backend_dir)

from googleapiclient.discovery import build

from config.google_config import config as google_config
from services.google_auth_service import GoogleAuthService


def main() -> None:
    folder_id = google_config.drive_root_folder_id
    if not folder_id:
        print("Error: GOOGLE_DRIVE_ROOT_FOLDER_ID is empty in .env", file=sys.stderr)
        sys.exit(1)

    auth = GoogleAuthService(google_config.token_path)
    creds = auth.get_credentials()
    if creds is None:
        print(
            f"Error: drive_token.json not found at {google_config.token_path}",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        service = build("drive", "v3", credentials=creds)
        folder = (
            service.files()
            .get(fileId=folder_id, fields="id,name")
            .execute()
        )

        print("Connection Successful")
        print(f"Folder Name: {folder.get('name')}")
        print(f"Folder ID: {folder.get('id')}")
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
