const List<String> kSymptoms = [
  'Radiating Pain',
  'Tingling Numbness',
  'Radiating pain originates in lower back, runs through buttocks, travels down one leg',
  'Joint Pain',
  'Stiffness',
  'Crepitus',
  'Swelling',
  'Chills',
  'Shivering',
  'Sweating',
  'Headaches',
  'Muscle Aches',
  'Fatigue',
  'Dehydration',
  'Loss of Appetite',
  'Sore Throat',
  'Difficulty Swallowing',
  'Constipation',
  'Lower Back Pain',
  'Neck Pain',
  'Neck Pain & Stiffness',
  'Radiating Pain & Numbness',
  'Weight Gain',
  'Dryness',
  'Weight Loss',
  'Anxiety & Irritability',
  'Excessive Thirst',
  'Frequent Urination',
  'Outer Elbow Pain',
  'Radiating Discomfort',
  'Severe Pain and Stiffness in Shoulder Joint',
  'Irregular Periods',
  'Abnormal Bleeding (Heavy)',
  'Infertility',
  'Heel Pain',
  'Loose Motion',
  'Vomiting',
  'Burning Micturation',
  'Flank or Back Pain',
  'Blood in Urine',
  'Painful Urination',
  'Nausea',
  'Dry Eyes',
  'Burning Eyes',
  'Chest Pain',
  'Burning Sensation in Chest',
  'Difficulty in Breathing',
  'Dizziness',
  'Anemia',
];

const List<Map<String, String>> kMedicines = [
  {'name': 'Maharasnadi Yog',             'type': 'Yog'},
  {'name': 'Raktapachak',                  'type': 'Yog'},
  {'name': 'Madhuyog',                     'type': 'Yog'},
  {'name': 'Avipattikar',                  'type': 'Churna'},
  {'name': 'Ashmarihar',                   'type': 'Yog'},
  {'name': 'Janusandhi Shoolhar',          'type': 'Yog'},
  {'name': 'Vatarakta Rujahar',            'type': 'Yog'},
  {'name': 'Talisadi Churna',              'type': 'Churna'},
  {'name': 'Sitopaladi Churna',            'type': 'Churna'},
  {'name': 'Hingvashtak Churna',           'type': 'Churna'},
  {'name': 'Bhaskar Lavan Churna',         'type': 'Churna'},
  {'name': 'Haridrakhand',                 'type': 'Khand'},
  {'name': 'Mahasudarshan',               'type': 'Churna'},
  {'name': 'Menses Formula',              'type': 'Formula'},
  {'name': 'Ansashoolhar',                 'type': 'Yog'},
  {'name': 'Bilvadi Churna',               'type': 'Churna'},
  {'name': 'Raktadab Yog',                 'type': 'Yog'},
  {'name': 'Triphala Churna',              'type': 'Churna'},
  {'name': 'Triphala Guggul',              'type': 'Guggul'},
  {'name': 'Sukh + Arsh',                 'type': 'Combination'},
  {'name': 'Raktarth Formula',             'type': 'Formula'},
  {'name': 'Karpuradi',                    'type': 'Yog'},
  {'name': 'RTI',                          'type': 'Formula'},
  {'name': 'Numo',                         'type': 'Formula'},
  {'name': 'Mansapachak',                  'type': 'Yog'},
  {'name': 'Eladi Churna',                 'type': 'Churna'},
  {'name': 'Madhukhwath',                  'type': 'Khwath'},
  {'name': 'Aargwadh Kapila',              'type': 'Yog'},
  {'name': 'Arogyavardhini',               'type': 'Vati'},
  {'name': 'Allerco',                      'type': 'Formula'},
  {'name': 'Asthiposhak Vati',             'type': 'Vati'},
  {'name': 'Brahmi Vati',                  'type': 'Vati'},
  {'name': 'Chandrakala Ras',              'type': 'Ras'},
  {'name': 'Chitrakadi Vati',              'type': 'Vati'},
  {'name': 'Crustone',                     'type': 'Formula'},
  {'name': 'Dhatri Loha',                  'type': 'Loha'},
  {'name': 'Diarid',                       'type': 'Formula'},
  {'name': 'Eladi Vati',                   'type': 'Vati'},
  {'name': 'Gandhak Rasayan',              'type': 'Rasayan'},
  {'name': 'Gandharva Haritaki',           'type': 'Yog'},
  {'name': 'Gudmar Ghan',                  'type': 'Ghan'},
  {'name': 'Rasapachak Vati',              'type': 'Vati'},
  {'name': 'Kamdudha',                     'type': 'Ras'},
  {'name': 'Kamdudha (M.Yu.)',             'type': 'Ras'},
  {'name': 'Kanaksundar Vati',             'type': 'Vati'},
  {'name': 'Krumighn Vati',               'type': 'Vati'},
  {'name': 'Kumari Asava',                 'type': 'Asava'},
  {'name': 'Kutaj Ghan',                   'type': 'Ghan'},
  {'name': 'Laghu Sutshekhar',             'type': 'Ras'},
  {'name': 'Laghu Malini Vasant',          'type': 'Ras'},
  {'name': 'Laxmi Vilas Ras',             'type': 'Ras'},
  {'name': 'Mansapachak Vati',             'type': 'Vati'},
  {'name': 'Medopachak',                   'type': 'Yog'},
  {'name': 'Navayas Loha Vati',            'type': 'Vati'},
  {'name': 'Pcyst-o-tab',                  'type': 'Tablet'},
  {'name': 'Pachak Vati',                  'type': 'Vati'},
  {'name': 'Rasapachak',                   'type': 'Yog'},
  {'name': 'Patolnimbadi Yog',             'type': 'Yog'},
  {'name': 'Pathyadi Vati',               'type': 'Vati'},
  {'name': 'Pravala Panchamrut',           'type': 'Ras'},
  {'name': 'Pravala Panchamrut (M.Yu.)',   'type': 'Ras'},
  {'name': 'Punarnava Mandur',             'type': 'Mandur'},
  {'name': 'Rajni Yog',                    'type': 'Yog'},
  {'name': 'Rajapravartini Vati',          'type': 'Vati'},
  {'name': 'Raktastambhak Vati',           'type': 'Vati'},
  {'name': 'Rasgandha',                    'type': 'Yog'},
  {'name': 'Sanshmani Vati',              'type': 'Vati'},
  {'name': 'Sariva Manjishta Vati',        'type': 'Vati'},
  {'name': 'Sarivadi Vati',               'type': 'Vati'},
  {'name': 'Shankh Vati',                 'type': 'Vati'},
  {'name': 'Shephali Vati',               'type': 'Vati'},
  {'name': 'Shwas Kuthar Ras',            'type': 'Ras'},
  {'name': 'Sukshma Triphala',            'type': 'Churna'},
  {'name': 'Sutagandha',                  'type': 'Yog'},
  {'name': 'Sutshekhar Ras',              'type': 'Ras'},
  {'name': 'Tapyadi Loha',                'type': 'Loha'},
  {'name': 'Tribhuvan Kirti',             'type': 'Ras'},
  {'name': 'Vatagajankush Ras',           'type': 'Ras'},
  {'name': 'Amrutadi Guggul',             'type': 'Guggul'},
  {'name': 'Gokshuradi Guggul',           'type': 'Guggul'},
  {'name': 'Kaishor Guggul',              'type': 'Guggul'},
  {'name': 'Kanchanar Guggul',            'type': 'Guggul'},
  {'name': 'Kukkutankhi Guggul',          'type': 'Guggul'},
  {'name': 'Lakshadi Guggul',             'type': 'Guggul'},
  {'name': 'Mahayograj Guggul',           'type': 'Guggul'},
  {'name': 'Yograj Guggul',               'type': 'Guggul'},
  {'name': 'Medohar Guggul',              'type': 'Guggul'},
  {'name': 'Panchatikta Ghrit Guggul',    'type': 'Guggul'},
  {'name': 'Punarnavadi Guggul',          'type': 'Guggul'},
  {'name': 'Rasnadi Guggul',              'type': 'Guggul'},
  {'name': 'Singhnad Guggul',             'type': 'Guggul'},
  {'name': 'Trayodashang Guggul',         'type': 'Guggul'},
];

// Ayurvedic dosage options (replace standard mg dosages)
const List<String> kDosageOptions = [
  '1 Tab', '2 Tab', '3 Tab',
  '1 tsp', '2 tsp', '1 tbsp',
  '500mg', '1g', '2g', '5g',
  '1 Sachet', '2 Sachet',
  '10ml', '15ml', '20ml', '30ml',
];

// Ayurvedic frequency options
const List<String> kFrequencyOptions = [
  'OD - Once Daily',
  'BD - Twice Daily',
  'TDS - Three Times Daily',
  'QID - Four Times Daily',
  'SOS - As Needed',
  'HS - At Bedtime',
  'Before Meals',
  'After Meals',
  'With Warm Water',
  'With Honey',
  'With Milk',
  'With Ghee',
  'Empty Stomach',
];

// Duration options
const List<String> kDurationOptions = [
  '3 days', '5 days', '7 days',
  '10 days', '14 days', '1 month',
  '2 months', '3 months', '6 months',
  'Ongoing',
];

class MedicalData {
  // ─── 50+ Common ICD-10 Diagnoses ───────────────────────────
  static const List<String> diagnoses = [
    'Essential Hypertension (I10)',
    'Type 2 Diabetes Mellitus (E11)',
    'Acute Upper Respiratory Infection (J06.9)',
    'Acute Bronchitis (J20.9)',
    'Pneumonia, Unspecified (J18.9)',
    'Migraine, Unspecified (G43.9)',
    'Gastro-Esophageal Reflux Disease without Esophagitis (K21.9)',
    'Generalized Anxiety Disorder (F41.1)',
    'Major Depressive Disorder, Unspecified (F32.9)',
    'Asthma, Unspecified (J45.9)',
    'Chronic Obstructive Pulmonary Disease, Unspecified (J44.9)',
    'Hyperlipidemia, Unspecified (E78.5)',
    'Hypothyroidism, Unspecified (E03.9)',
    'Urinary Tract Infection, Site Not Specified (N39.0)',
    'Acute Tonsillitis, Unspecified (J03.9)',
    'Acute Pharyngitis, Unspecified (J02.9)',
    'Allergic Rhinitis, Unspecified (J30.9)',
    'Osteoarthritis, Unspecified (M19.9)',
    'Rheumatoid Arthritis, Unspecified (M06.9)',
    'Iron Deficiency Anemia, Unspecified (D50.9)',
    'Vitamin D Deficiency, Unspecified (E55.9)',
    'Vitamin B12 Deficiency, Unspecified (E53.8)',
    'Acute Gastritis (K29.0)',
    'Irritable Bowel Syndrome without Diarrhea (K58.9)',
    'Gout, Unspecified (M10.9)',
    'Lumbago with Sciatica (M54.4)',
    'Cervicalgia (M54.2)',
    'Fibromyalgia (M79.7)',
    'Chronic Fatigue Syndrome (G93.3)',
    'Acne Vulgaris (L70.0)',
    'Atopic Dermatitis, Unspecified (L20.9)',
    'Psoriasis, Unspecified (L40.9)',
    'Obesity, Unspecified (E66.9)',
    'Insomnia, Unspecified (G47.0)',
    'Vertigo, Unspecified (R42)',
    'Tension Headache, Unspecified (G44.2)',
    'Acute Sinusitis, Unspecified (J01.9)',
    'Otitis Media, Unspecified (H66.9)',
    'Conjunctivitis, Unspecified (H10.9)',
    'Polycystic Ovarian Syndrome (E28.2)',
    'Benign Prostatic Hyperplasia (N40)',
    'Calculus of Kidney (N20.0)',
    'Haemorrhoids, Unspecified (I84.9)',
    'Constipation, Unspecified (K59.0)',
    'Diarrhoea, Presumed Infectious (A09)',
    'Alopecia Areata (L63.9)',
    'Candidiasis, Unspecified (B37.9)',
    'Tinea Corporis (B35.4)',
    'Dry Eye Syndrome (H04.1)',
    'Chholelithiasis (K80.2)',
    'Hyperthyroidism, Unspecified (E05.9)',
  ];
}
