import 'dart:ui' show Locale;

const Map<String, String> _marathiNames = {
  'maharasnadi yog': 'महारास्नादी योग',
  'raktapachak': 'रक्तपाचक',
  'madhuyog': 'मधुयोग',
  'avipattikar': 'अविपत्तिकर',
  'ashmarihar': 'अश्मरीहर',
  'janusandhi shoolhar': 'जानुसंधी शूलहर',
  'vatarakta rujahar': 'वातरक्त रुजाहर',
  'talisadi churna': 'तळिसादी चूर्ण',
  'sitopaladi churna': 'सितोपलादी चूर्ण',
  'hingvashtak churna': 'हिंग्वाष्टक चूर्ण',
  'bhaskar lava churna': 'भास्कर लवण चूर्ण',
  'haridrakhand': 'हरिद्राखंड',
  'mahasudarshan': 'महासुदर्शन',
  'menses formula': 'मेन्सेस फॉर्म्युला',
  'ansashoolhar': 'अंशशूलहर',
  'bilvadi churna': 'बिल्वादी चूर्ण',
  'raktadab yog': 'रक्तदाब योग',
  'triphala churna': 'त्रिफळा चूर्ण',
  'triphala guggul': 'त्रिफळा गुग्गुल',
  'sukh + arsh': 'सुख + अर्श',
  'raktarth formula': 'रक्तार्त फॉर्म्युला',
  'karpuradi': 'कर्पूरादी',
  'rti': 'आर.टी.आय.',
  'numo': 'न्युमो',
  'mansapachak': 'मांसपाचक',
  'eladi churna': 'एलादी चूर्ण',
  'madhukhwath': 'मधुख्वाथ',
  'aargwadh kapila': 'आरग्वध कपिला',
  'arogyavardhini': 'आरोग्यवर्धिनी',
  'allerco': 'अलर्को',
  'asthiposhak vati': 'अस्थिपोषक वटी',
  'brahmi vati': 'ब्राह्मी वटी',
  'chandrakala ras': 'चंद्रकला रस',
  'chitrakadi vati': 'चित्रकादी वटी',
  'crustone': 'क्रस्टोन',
  'dhatri loha': 'धात्री लोह',
  'diarid': 'डायरिड',
  'eladi vati': 'एलादी वटी',
  'gandhak rasayan': 'गंधक रसायन',
  'gandharva haritaki': 'गंधर्व हरितकी',
  'gudmar ghan': 'गुडमार घन',
  'rasapachak vati': 'रसपाचक वटी',
  'kamdudha': 'कामदुध',
  'kamdudha (m.yu.)': 'कामदुध (म.यु.)',
  'kanaksundar vati': 'कनकसुंदर वटी',
  'krumighn vati': 'कृमिघ्न वटी',
  'kumari asava': 'कुमारी आसव',
  'kutaj ghan': 'कुटज घन',
  'laghu sutshekhar': 'लघु सुतशेखर',
  'laghu malini vasant': 'लघु मालिनी वसंत',
  'laxmi vilas ras': 'लक्ष्मी विलास रस',
  'mansapachak vati': 'मांसपाचक वटी',
  'medopachak': 'मेदोपाचक',
  'navayas loha vati': 'नवयस लोह वटी',
  'pcyst-o-tab': 'पी.सिस्ट-ओ-टॅब',
  'pachak vati': 'पाचक वटी',
  'rasapachak': 'रसपाचक',
  'patolnimbadi yog': 'पाटोलनिंबादी योग',
  'pathyadi vati': 'पाथ्यादी वटी',
  'pravala panchamrut': 'प्रवाल पंचामृत',
  'pravala panchamrut (m.yu.)': 'प्रवाल पंचामृत (म.यु.)',
  'punarnava mandur': 'पुनर्नवा मंदुर',
  'rajni yog': 'रज्ञी योग',
  'rajapravartini vati': 'राजप्रवर्तिनी वटी',
  'raktastambhak vati': 'रक्तस्तंभक वटी',
  'rasgandha': 'रसगंधा',
  'sanshmani vati': 'संश्मनी वटी',
  'sariva manjishta vati': 'सारिवा मञ्जिष्ठा वटी',
  'sarivadi vati': 'सारिवादी वटी',
  'shankh vati': 'शंख वटी',
  'shephali vati': 'शेफाली वटी',
  'shwas kuthar ras': 'श्वास कुठार रस',
  'sukshma triphala': 'सूक्ष्म त्रिफळा',
  'sutagandha': 'सुतगंधा',
  'sutshekhar ras': 'सुतशेखर रस',
  'tapyadi loha': 'ताप्यादी लोह',
  'tribhuvan kirti': 'त्रिभुवन कीर्ति',
  'vatagajankush ras': 'वातगजांकुश रस',
  'amrutadi guggul': 'अमृतादी गुग्गुल',
  'gokshuradi guggul': 'गोक्षुरादी गुग्गुल',
  'kaishor guggul': 'कैशोर गुग्गुल',
  'kanchanar guggul': 'कांचनार गुग्गुल',
  'kukkutankhi guggul': 'कुक्कुटांखी गुग्गुल',
  'lakshadi guggul': 'लक्षादी गुग्गुल',
  'mahayograj guggul': 'महायोगराज गुग्गुल',
  'yograj guggul': 'योगराज गुग्गुल',
  'medohar guggul': 'मेदोहर गुग्गुल',
  'panchatikta ghrit guggul': 'पंचतिक्त घृत गुग्गुल',
  'punarnavadi guggul': 'पुनर्नवादी गुग्गुल',
  'rasnadi guggul': 'रस्नादी गुग्गुल',
  'singhnad guggul': 'सिंहनाद गुग्गुल',
  'trayodashang guggul': 'त्रयोदशांग गुग्गुल',
  'ashwagandha': 'अश्वगंधा',
  'triphala': 'त्रिफळा',
  'chyawanprash': 'च्यवनप्राश',
  'dashmoolarishta': 'दशमूलारिष्ट',
  'giloy': 'गुळवेल',
  'haritaki': 'हिरडा',
  'amalaki': 'आवळा',
  'bibhitaki': 'बेहडा',
};

const Map<String, String> _marathiTypes = {
  'yog': 'योग',
  'churna': 'चूर्ण',
  'vati': 'वटी',
  'ras': 'रस',
  'guggul': 'गुग्गुल',
  'formula': 'फॉर्म्युला',
  'khand': 'खंड',
  'khwath': 'क्वाथ',
  'rasayan': 'रसायन',
  'loha': 'लोह',
  'ghan': 'घन',
  'mandur': 'मंदुर',
  'asava': 'आसव',
  'tablet': 'गोळी',
  'combination': 'कॉम्बिनेशन',
};

String localizeMedicineName(String englishName, Locale locale) {
  if (locale.languageCode != 'mr') return englishName;
  final key = englishName.toLowerCase().trim();
  return _marathiNames[key] ?? englishName;
}

String localizeMedicineType(String englishType, Locale locale) {
  if (locale.languageCode != 'mr') return englishType;
  final key = englishType.toLowerCase().trim();
  return _marathiTypes[key] ?? englishType;
}
